name: '${project.name}'
main: de.schottky.turnstile.TurnstilePlugin
version: '${project.version}'
description: '${project.description}'
author: Schottky
api-version: '1.15'
softdepend:
  - Vault
  - Citizens
commands:
  turnstile:
    description: Base-command for everything turnstile-related
    usage: /turnstile <sub-command> or /ts <sub-command>
    permission: ts.command.base
    aliases:
      - ts